# 图片生成服务配置
# 请在 Web 界面的"设置"页面中配置 API Key
active_provider: default
providers:
  default:
    api_key: ""
    base_url: https://api.openai.com/v1
    high_concurrency: false
    model: dall-e-3
    type: image_api
  # modelscope:
  #   api_key: ""
  #   base_url: https://api-inference.modelscope.cn
  #   high_concurrency: false
  #   model: Tongyi-MAI/Z-Image-Turbo
  #   type: modelscope
  # replicate:
  #   api_key: ""
  #   default_aspect_ratio: 3:4
  #   high_concurrency: false
  #   model: prunaai/z-image-turbo:0870559624690b3709350177b9d521d84e54d297026d725358b8f73193429e91
  #   type: replicate
