name: Create Release

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get Version
        id: get_version
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          else
            echo "VERSION=Manual-Trig" >> $GITHUB_OUTPUT
          fi

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: ${{ steps.get_version.outputs.VERSION }}
          name: MotifLab ${{ steps.get_version.outputs.VERSION }}
          generate_release_notes: true
          body: |
            ## 🚀 MotifLab Release ${{ steps.get_version.outputs.VERSION }}

            MotifLab 图文大模型生成引擎版本更新！
            The latest version of MotifLab has been released!

            *项目为无需预构建的全源码版本，可以直接下载下方的打包源码（Source code）按照 README 运行。*
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
